/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat
         * @description Run one synchronous collaboration turn in a worker thread.
         */
        post: operations["chat_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat Stream
         * @description SSE 原生流式聊天(token + 安全运行事件)。
         *
         *     会话忙时与 POST /chat 行为一致:立即返回普通 JSON(session_busy),
         *     不是 SSE 流;正常时返回 text/event-stream,事件按 sequence 增量推送。
         *
         *     from_sequence(D1-T3 断线重连):客户端断线重连时传上次收到的最新
         *     sequence；若 checkpoint 中最近一轮已结束,服务端回放剩余事件并补发
         *     权威 message_end + done；若仍是中间态则要求客户端继续等待，绝不
         *     重跑。默认 0 表示发新消息并启动新 run。
         */
        post: operations["chat_stream_chat_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Feedback
         * @description 记录一条用户反馈,返回受理确认。
         *
         *     只存脱敏引用字段:record 固定 7 个键,不含消息全文;user_id 为
         *     None 时落 null(匿名反馈),与会话 API 的匿名语义一致。
         */
        post: operations["submit_feedback_feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload File
         * @description 上传聊天附件(按用户隔离存储),返回受控下载回执。
         *
         *     - 扩展名白名单 / 大小上限 / 空文件都在 API 层拦截为 422(大小在
         *       逐块读取时累计,不能信 Content-Length);
         *     - 存储目录按 user_key 隔离(消毒后的 X-User-Id,None → anonymous);
         *       落盘名是 uuid4().hex + 白名单后缀,原始文件名只作展示字段返回;
         *     - 同步写盘走 run_in_threadpool,不阻塞事件循环;写盘失败(OSError
         *       等)统一映射 500 internal_error,不泄底层细节。
         */
        post: operations["upload_file_files_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{file_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Uploaded File
         * @description 按受控下载路径提供已上传文件(用户隔离校验)。
         *
         *     - file_id 必须是安全段(见 _is_safe_segment),不匹配一律 404;
         *     - 存储路径 {root}/{user_key}/{file_id}:user_key 由当前 X-User-Id
         *       消毒得出(与上传同源)——他人目录下的 uuid 文件名不可枚举,
         *       等价于文件不存在,统一 404(不返回 403,避免泄露目录存在性);
         *     - media_type 按扩展名映射,与上传响应的 content_type 同源
         *       (_UPLOAD_CONTENT_TYPES);底层读盘异常映射 500。
         */
        get: operations["get_uploaded_file_files__file_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description 存活探针；lifespan 装配后附带检索与 OCR 诊断（H-T1 / P0-6）。
         *
         *     - lifespan 未跑（如单测直接 create_app()）或诊断未就绪：保持
         *       {"status": "ok"} 现状，不破坏既有探针语义与测试；
         *     - lifespan 跑过：附加 retrieval 字段（mode / embedding_provider /
         *       vector_dimension）与 ocr 字段（enabled，P0-6：图片附件识别
         *       能力是否在线），运维据此判断可选能力状态。诊断只含状态字段，
         *       绝不含任何文件路径。
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge/chunks/{chunk_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Chunk
         * @description 按 chunk_id 取回分块原文(I2 查看原文)。
         *
         *     - 未命中(不存在 / 空白 / 超长 chunk_id):404 chunk_not_found——
         *       chunk_id 是引用凭证,引用指向不存在的分块属「资源不存在」,
         *       与检索「空结果不报错」语义刻意不同(检索是查询,这里是定位);
         *     - content 上限 CHUNK_CONTENT_MAX_LENGTH 截断(防撑爆响应体);
         *     - 只暴露 chunk 文本 + 逻辑引用,不暴露文件路径(models 层
         *       _validate_logical_source 保证)。
         */
        get: operations["get_chunk_knowledge_chunks__chunk_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Documents
         * @description 列出文档元数据:词法库聚合(脚本入库教材 + 已落库上传) + 注册表合并。
         *
         *     I1 起 core 提供清单能力(SqliteKnowledgeCatalog):直接聚合词法库
         *     的 chunks / ingest_marks / metadata,脚本入库的教材首次对 API
         *     可见。API 上传文档成功入库后同样出现在聚合结果里,因此注册表
         *     (app.state.knowledge_documents)只作为「未落库条目」的防御性兜底
         *     合并(理论上不触发,保留以兼容极端时序)。
         */
        get: operations["list_documents_knowledge_documents_get"];
        put?: never;
        /**
         * Upload Document
         * @description 上传 txt/pdf 文档入库(幂等替换),返回文档元数据回执。
         *
         *     - 扩展名白名单 / 大小上限 / 空文件都在 API 层拦截为 422,不依赖
         *       core 运行时异常(大小在逐块读取时累计,不能信 Content-Length);
         *     - document_id = 上传文件名 stem,source = 上传文件名(逻辑标识,
         *       不泄漏文件系统路径):重传同名文件 → 同一 document_id → core
         *       替换语义,旧内容被新内容覆盖;
         *     - loader 解析失败(空文件/无文本/损坏 PDF)映射 422 invalid_request
         *       (内容不可解析属请求问题);入库内部异常映射 500 internal_error,
         *       不泄底层细节。
         */
        post: operations["upload_document_knowledge_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Document
         * @description 删除文档(幂等:文档不存在也返回 204,不报 404)。
         *
         *     core 的 KnowledgeService.delete_document 是幂等删除(不存在不抛错),
         *     且 API 层没有文档存在性查询能力(原因见 list_documents 注释),无法
         *     区分「存在/不存在」。按 core 语义,删除不存在的文档同样返回 204——
         *     重复删除/清理任务幂等安全;待 core 提供清单/存在性能力后再增加
         *     404 区分。注册表同步移除该条目。
         */
        delete: operations["delete_document_knowledge_documents__document_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge/documents/{document_id}/chunks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Document Chunks
         * @description 列出某文档的分块(I2 浏览):分页,只带定位信息与摘要。
         *
         *     - offset 从 0 起、limit 默认 20;limit 由 FastAPI Query 参数拦截
         *       越界(offset>=0、1<=limit<=CHUNK_LIST_PAGE_SIZE_MAX,422),不
         *       依赖 core 校验;
         *     - chunks_of_document 按 (start, chunk_id) 排序(与 ingest 顺序一致),
         *       分页截取稳定;
         *     - 条目只带摘要(SUMMARY_MAX_LENGTH 截断),完整原文经
         *       GET /knowledge/chunks/{chunk_id} 获取——列表页先看摘要、点开
         *       再看全文;
         *     - 文档不存在:空 items(分页在空集合上就是空),不报 404——与
         *       删除端点「不存在幂等」同一哲学(见 delete_document 注释);
         *     - 用服务层的 chunk 能力做「索引未实现 chunk 的兜底」:若索引
         *       未实现 chunk(getter 缺失),列表仍可用 chunks_of_document 逻辑?
         *       ——不:本端点直接依赖 chunks_of_document(索引实现本身),与
         *       chunk 单条端点无关。分页在 Python 侧完成(全部取出后切片),
         *       数据量(单文档最多数千 chunk)可接受。
         */
        get: operations["list_document_chunks_knowledge_documents__document_id__chunks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Knowledge Overview
         * @description 知识库总览(I1):语料统计 + 每篇文档元数据,一次请求覆盖教师端。
         *
         *     - 无 catalog 装配(部署问题):503 knowledge_unavailable(与检索
         *       端点同一稳定错误码);
         *     - 空库(从未入库):stats 全 0、documents 空列表,不报错(与
         *       「空库检索返回空」语义一致);
         *     - 只读聚合,不触发 embedding 模型加载(数据全部来自词法库)。
         */
        get: operations["knowledge_overview_knowledge_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search Knowledge
         * @description 检索知识库,返回命中的脱敏摘要与逻辑引用。
         *
         *     - 空库返回空 hits,不报错(与 core 语义一致);
         *     - top_k 已被 Pydantic 拦截在 1-10,core 的 ValueError 兜底不会
         *       触发(见 KnowledgeSearchRequest 注释);
         *     - service.search 内部异常统一映射 500 internal_error,不泄底层
         *       细节(与 api/feedback 的存储异常处理同构)。
         */
        post: operations["search_knowledge_knowledge_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/learning/diagnosis/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Diagnosis Summary
         * @description 返回学情诊断摘要（默认当前用户；student_id 供教师视角查询）。
         *
         *     边界与降级见模块 docstring：v1 的 student_id 查询是演示环境可信
         *     声明（无鉴权），生产需待认证落地；store 缺失或空数据返回空报告。
         */
        get: operations["diagnosis_summary_learning_diagnosis_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sessions
         * @description List only the current user's sessions.
         */
        get: operations["list_sessions_sessions_get"];
        put?: never;
        /**
         * Create Session
         * @description Create a session within the current user's isolated namespace.
         */
        post: operations["create_session_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Archive Session
         * @description Archive an active session without revealing another user's session.
         */
        post: operations["archive_session_sessions__session_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/handoff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Pending Handoff
         * @description Return the current user's pending handoff, if any.
         */
        get: operations["get_pending_handoff_sessions__session_id__handoff_get"];
        put?: never;
        /**
         * Decide Handoff
         * @description Confirm or reject the current handoff, then return its graph transition.
         */
        post: operations["decide_handoff_sessions__session_id__handoff_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Session History
         * @description Return only safe history fields for the current user's session.
         */
        get: operations["get_session_history_sessions__session_id__messages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Session Process
         * @description 返回 checkpoint 中可回放的思考、工具与协作过程快照。
         */
        get: operations["get_session_process_sessions__session_id__process_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/tool-approval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Pending Tool Approval
         * @description Return the exact validated invocation currently awaiting consent.
         */
        get: operations["get_pending_tool_approval_sessions__session_id__tool_approval_get"];
        put?: never;
        /**
         * Decide Tool Approval
         * @description Confirm or reject one exact invocation, then finish the graph turn.
         */
        post: operations["decide_tool_approval_sessions__session_id__tool_approval_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/tool-approval/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stream Tool Approval
         * @description Resume one exact tool gate and stream terminal/model output as SSE.
         */
        post: operations["stream_tool_approval_sessions__session_id__tool_approval_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/workspace-roots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Workspace Root
         * @description Authorize one additional directory for this session's file tools.
         */
        post: operations["add_workspace_root_sessions__session_id__workspace_roots_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stats Overview
         * @description 返回当前用户的学习进度基础统计(只读聚合)。
         */
        get: operations["stats_overview_stats_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/directories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Workspace Directories
         * @description Browse immediate directories without exposing files or file contents.
         */
        get: operations["list_workspace_directories_workspaces_directories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspaces/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate Workspace
         * @description Resolve a typed path before the user creates or updates a session.
         */
        post: operations["validate_workspace_workspaces_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AddWorkspaceRootRequest
         * @description One user-authorized additional workspace directory.
         */
        AddWorkspaceRootRequest: {
            /** Path */
            path: string;
        };
        /**
         * AgentRole
         * @description Public collaborative-agent roles.
         * @enum {string}
         */
        AgentRole: "supervisor" | "teaching_assistant" | "learning_assistant" | "evaluator";
        /**
         * ApiErrorCode
         * @description Stable HTTP API errors not emitted by a graph run.
         * @enum {string}
         */
        ApiErrorCode: "invalid_request" | "internal_error" | "handoff_not_pending" | "tool_approval_not_pending" | "session_already_exists" | "session_busy" | "session_not_found" | "knowledge_unavailable";
        /**
         * Attachment
         * @description 聊天消息附件引用(D7-T1 契约扩展预留)。
         *
         *     - file_id / name / content_type / size 由上传回执(FILE-UPLOAD)填充;
         *     - 骨架期 chat 路由忽略该字段不影响现有行为(见 ChatRequest 注释),由
         *       D7-T3 或后续 core 能力决定如何进入模型上下文。
         */
        Attachment: {
            /**
             * Content Type
             * @default null
             */
            content_type?: string | null;
            /** File Id */
            file_id: string;
            /** Name */
            name: string;
            /** Size */
            size: number;
        };
        /** Body_upload_document_knowledge_documents_post */
        Body_upload_document_knowledge_documents_post: {
            /** File */
            file: string;
        };
        /** Body_upload_file_files_post */
        Body_upload_file_files_post: {
            /** File */
            file: string;
        };
        /**
         * ChatRequest
         * @description One synchronous user message for a session.
         */
        ChatRequest: {
            /**
             * Attachments
             * @default null
             */
            attachments?: components["schemas"]["Attachment"][] | null;
            /** Message */
            message: string;
            /** Session Id */
            session_id: string;
        };
        /**
         * ChatResponse
         * @description The synchronous response contract shared by chat and approval routes.
         */
        ChatResponse: {
            /** @default null */
            current_agent?: components["schemas"]["AgentRole"] | null;
            /** Events */
            events?: components["schemas"]["RunEvent"][];
            /** @default null */
            grading?: components["schemas"]["GradingResultDto"] | null;
            /** @default null */
            message?: components["schemas"]["Message"] | null;
            /** @default null */
            pending_handoff?: components["schemas"]["PendingHandoff"] | null;
            /** @default null */
            pending_tool_approval?: components["schemas"]["PendingToolApproval"] | null;
            /**
             * References
             * @default null
             */
            references?: components["schemas"]["Citation"][] | null;
            /** @default null */
            run_error?: components["schemas"]["RunError"] | null;
            /**
             * Run Id
             * @default null
             */
            run_id?: string | null;
            /** Session Id */
            session_id: string;
            /** @default null */
            task_plan?: components["schemas"]["TaskPlan"] | null;
            /**
             * Task Results
             * @default null
             */
            task_results?: components["schemas"]["TaskResult"][] | null;
        };
        /**
         * ChunkDetailResponse
         * @description 单个分块原文(I2 查看原文):内容 + 配套引用凭证。
         *
         *     content 上限 8KB(后端截断,防撑爆响应,见 api/knowledge.py 的
         *     CHUNK_CONTENT_MAX_LENGTH);citation 与检索命中的 Citation 同构
         *     (document_id / source / page / chunk_id),可直接用于「查看原文」
         *     跳转与引用展示。
         */
        ChunkDetailResponse: {
            citation: components["schemas"]["Citation"];
            /** Content */
            content: string;
        };
        /**
         * ChunkListEntry
         * @description 分块列表条目(I2 浏览):不带全文,只带定位信息与摘要。
         *
         *     summary 由 chunk 内容截断生成(与检索命中同口径,上限
         *     SUMMARY_MAX_LENGTH);完整原文经 GET /knowledge/chunks/{chunk_id}
         *     单独获取——列表页先看摘要,点开再看全文。
         */
        ChunkListEntry: {
            /** Chunk Id */
            chunk_id: string;
            /**
             * End
             * @default 0
             */
            end?: number;
            /**
             * Page
             * @default null
             */
            page?: number | null;
            /**
             * Start
             * @default 0
             */
            start?: number;
            /** Summary */
            summary: string;
        };
        /**
         * ChunkListResponse
         * @description 某文档的分块分页列表(I2 浏览)。
         *
         *     total 是该文档全部分块数(不分页),供前端算分页;items 为当前
         *     页条目(按 start, chunk_id 排序,见 index.py chunks_of_document)。
         */
        ChunkListResponse: {
            /** Document Id */
            document_id: string;
            /** Items */
            items: components["schemas"]["ChunkListEntry"][];
            /** Total */
            total: number;
        };
        /**
         * Citation
         * @description A safe reference placeholder for future retrieval-backed responses.
         */
        Citation: {
            /** Chunk Id */
            chunk_id: string;
            /** Document Id */
            document_id: string;
            /**
             * Page
             * @default null
             */
            page?: number | null;
            /** Source */
            source: string;
        };
        /**
         * CreateSessionRequest
         * @description Optional client-selected ID for a new session.
         */
        CreateSessionRequest: {
            /**
             * Session Id
             * @default null
             */
            session_id?: string | null;
            /**
             * Workspace Root
             * @default null
             */
            workspace_root?: string | null;
        };
        /**
         * DiagnosisKnowledgePoint
         * @description 学情诊断：一个知识点的作答聚合（六大功能 P3-15）。
         */
        DiagnosisKnowledgePoint: {
            /** Accuracy */
            accuracy: number;
            /** Attempts */
            attempts: number;
            /** Correct */
            correct: number;
            /** Knowledge Point */
            knowledge_point: string;
            /**
             * Last At
             * @default null
             */
            last_at?: string | null;
        };
        /**
         * DiagnosisSummary
         * @description 学情诊断摘要（六大功能 P3-15）。
         *
         *     数据源是 learning_records 的 SQL 聚合（确定性规则：预警 =
         *     attempts≥2 且加权正确率<0.6，见 core/learning/store.py），LLM
         *     叙述只出现在对话内诊断报告，不在本契约里。
         */
        DiagnosisSummary: {
            /** Knowledge Points */
            knowledge_points?: components["schemas"]["DiagnosisKnowledgePoint"][];
            /**
             * Total Attempts
             * @default 0
             */
            total_attempts?: number;
            /**
             * Uncategorized Attempts
             * @default 0
             */
            uncategorized_attempts?: number;
            /**
             * User Id
             * @default null
             */
            user_id?: string | null;
            /** Weak Points */
            weak_points?: string[];
        };
        /**
         * ErrorCode
         * @description Stable API error codes aligned with the current Core classification.
         * @enum {string}
         */
        ErrorCode: "tool_unknown" | "tool_unauthorized" | "tool_invalid_arguments" | "tool_execution_failed" | "tool_timeout" | "tool_no_progress" | "tool_budget_exceeded" | "tool_approval_rejected" | "tool_approval_queue_limit" | "model_call_failed" | "react_iteration_limit" | "graph_handoff_limit" | "graph_switch_limit" | "graph_invalid_target" | "graph_aggregation_invalid" | "agent_output_invalid";
        /**
         * ErrorDetail
         * @description A sanitized stable API error.
         */
        ErrorDetail: {
            error_code: components["schemas"]["ApiErrorCode"];
            /** Message */
            message: string;
        };
        /**
         * ErrorResponse
         * @description FastAPI's standard error envelope.
         */
        ErrorResponse: {
            detail: components["schemas"]["ErrorDetail"];
        };
        /**
         * FeedbackRating
         * @description 用户反馈评分方向。
         * @enum {string}
         */
        FeedbackRating: "up" | "down";
        /**
         * FeedbackRequest
         * @description 用户反馈请求体(只收脱敏引用字段,不收消息全文)。
         */
        FeedbackRequest: {
            /**
             * Comment
             * @default null
             */
            comment?: string | null;
            /**
             * Error Code
             * @default null
             */
            error_code?: string | null;
            /**
             * Message Id
             * @default null
             */
            message_id?: string | null;
            rating: components["schemas"]["FeedbackRating"];
            /** Session Id */
            session_id: string;
        };
        /**
         * FeedbackResponse
         * @description 反馈受理确认。
         */
        FeedbackResponse: {
            /**
             * Received
             * @default true
             */
            received?: boolean;
        };
        /**
         * FileUploadResponse
         * @description 文件上传回执(D7-T1):url 为受控下载的相对路径。
         *
         *     - file_id 是服务端生成的 uuid4().hex + 白名单后缀(落盘名),url 形如
         *       /files/{file_id}——客户端凭 url 即可 GET 下载,url 不含原始文件名
         *       (后者只作展示字段 name);
         *     - content_type 由服务端按扩展名映射,不信任客户端伪造的类型;
         *     - name 是原始文件名(仅展示用;落盘名是 uuid,见 api/files.py 的
         *       防穿越设计)。
         */
        FileUploadResponse: {
            /** Content Type */
            content_type: string | null;
            /** File Id */
            file_id: string;
            /** Name */
            name: string;
            /** Size */
            size: number;
            /** Url */
            url: string;
        };
        /**
         * GradingItemDto
         * @description 一道题的批改结论（六大功能 P2-12；与 core GradingItem 同构）。
         */
        GradingItemDto: {
            /**
             * Error Tag
             * @default null
             */
            error_tag?: string | null;
            /**
             * Feedback
             * @default
             */
            feedback?: string;
            /**
             * Knowledge Point
             * @default null
             */
            knowledge_point?: string | null;
            /** Max Score */
            max_score: number;
            /** Question Id */
            question_id: string;
            /** Score */
            score: number;
        };
        /**
         * GradingResultDto
         * @description 一次批改的结构化结论（六大功能 P2-12；与 core GradingResult 同构）。
         *
         *     total_score / max_total_score 由核心侧确定性汇总（不信任模型自报），
         *     语义见 core.state.GradingResult 注释。前端渲染时须标注「建议评分，
         *     教师复核」（LLM 主观题评分的既有产品口径）。
         */
        GradingResultDto: {
            /** Items */
            items: components["schemas"]["GradingItemDto"][];
            /** Max Total Score */
            max_total_score: number;
            /**
             * Overall Comment
             * @default
             */
            overall_comment?: string;
            /** Total Score */
            total_score: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HandoffDecisionAction
         * @description Approval actions for one pending handoff interrupt.
         * @enum {string}
         */
        HandoffDecisionAction: "confirm" | "reject" | "modify";
        /**
         * HandoffDecisionRequest
         * @description A confirmation, rejection, or modification for one pending handoff interrupt.
         */
        HandoffDecisionRequest: {
            action: components["schemas"]["HandoffDecisionAction"];
            /** Interrupt Id */
            interrupt_id: string;
            /**
             * @description The modified target worker; only valid when action is modify.
             * @default null
             */
            target_agent?: components["schemas"]["WorkerAgentRole"] | null;
            /**
             * Task Content
             * @description The modified task content; only valid when action is modify.
             * @default null
             */
            task_content?: string | null;
        };
        /**
         * HandoffRequest
         * @description The information a user reviews before a worker handoff.
         */
        HandoffRequest: {
            /**
             * Plan Step Sequence
             * @default null
             */
            plan_step_sequence?: number | null;
            target_agent: components["schemas"]["WorkerAgentRole"];
            /** Task Content */
            task_content: string;
        };
        /**
         * KnowledgeBaseStatsDto
         * @description 知识库语料统计(I1):教师端总览卡数据源。
         *
         *     total_pages 可空(纯 txt 语料无页概念时为 None);frontmatter_chunks
         *     单独给出供教师了解噪音占比(检索侧默认排除,见 service.py 的
         *     suppress_frontmatter)。
         */
        KnowledgeBaseStatsDto: {
            /**
             * Frontmatter Chunks
             * @default 0
             */
            frontmatter_chunks?: number;
            /** Total Chunks */
            total_chunks: number;
            /** Total Documents */
            total_documents: number;
            /**
             * Total Pages
             * @default null
             */
            total_pages?: number | null;
        };
        /**
         * KnowledgeDocumentInfoDto
         * @description 文档元数据(I1 清单能力):与 core catalog 的 KnowledgeDocumentInfo 同构。
         *
         *     title / subjects / difficulty / ingested_at 可空:脚本入库的教材
         *     由 manifest 注入元数据(title/subjects/difficulty)与 ingest_marks
         *     时间;API 上传文档无这些字段时为 None。chunk_count 恒为整数。
         */
        KnowledgeDocumentInfoDto: {
            /**
             * Chunk Count
             * @default 0
             */
            chunk_count?: number;
            /**
             * Difficulty
             * @default null
             */
            difficulty?: string | null;
            /** Document Id */
            document_id: string;
            /**
             * Ingested At
             * @default null
             */
            ingested_at?: string | null;
            /**
             * Page Count
             * @default null
             */
            page_count?: number | null;
            /** Source */
            source: string;
            /** Subjects */
            subjects?: string[];
            /**
             * Title
             * @default null
             */
            title?: string | null;
        };
        /**
         * KnowledgeDocumentListEntry
         * @description 知识库文档列表条目(只读元数据,不含内容)。
         *
         *     page_count / chunk_count 可空:txt 无页概念、core 未来接入清单
         *     能力前由 API 层留空(见 api/knowledge.py 的 list_documents 注释)。
         */
        KnowledgeDocumentListEntry: {
            /**
             * Chunk Count
             * @default null
             */
            chunk_count?: number | null;
            /** Document Id */
            document_id: string;
            /**
             * Page Count
             * @default null
             */
            page_count?: number | null;
            /** Source */
            source: string;
        };
        /**
         * KnowledgeDocumentListResponse
         * @description 文档清单响应(当前恒为空列表,原因见 list_documents 路由注释)。
         */
        KnowledgeDocumentListResponse: {
            /** Documents */
            documents: components["schemas"]["KnowledgeDocumentListEntry"][];
        };
        /**
         * KnowledgeDocumentUploadResponse
         * @description 上传解析结果:文档已入库(幂等替换)后的元数据回执。
         */
        KnowledgeDocumentUploadResponse: {
            /**
             * Chunk Count
             * @default null
             */
            chunk_count?: number | null;
            /** Document Id */
            document_id: string;
            /**
             * Page Count
             * @default null
             */
            page_count?: number | null;
            /** Source */
            source: string;
        };
        /**
         * KnowledgeOverviewResponse
         * @description 知识库总览:统计 + 每篇文档元数据(I1,一次请求覆盖教师端)。
         *
         *     documents 与 stats 同源(同一词法库聚合);阈值/重排器等检索
         *     配置装配状态预留字段(I3/I10,本期不填)。
         */
        KnowledgeOverviewResponse: {
            /** Documents */
            documents: components["schemas"]["KnowledgeDocumentInfoDto"][];
            stats: components["schemas"]["KnowledgeBaseStatsDto"];
        };
        /**
         * KnowledgeSearchRequest
         * @description 知识库检索请求。
         *
         *     top_k 必须由 API 层校验(Field ge/le)拦截在 422,不得依赖 core
         *     的 ValueError 运行时兜底(会变 500);query 的空白拦截与
         *     ChatRequest.reject_blank_text 同构(core 对空白 query 抛
         *     ValueError,同样要拦在 API 层)。
         */
        KnowledgeSearchRequest: {
            /** Query */
            query: string;
            /**
             * Top K
             * @default 5
             */
            top_k?: number;
        };
        /**
         * KnowledgeSearchResponse
         * @description 检索结果(空库返回空 hits,不报错)。
         */
        KnowledgeSearchResponse: {
            /** Hits */
            hits: components["schemas"]["SearchHitDto"][];
        };
        /**
         * Message
         * @description A safe user or assistant message.
         */
        Message: {
            /** @default null */
            agent?: components["schemas"]["AgentRole"] | null;
            /**
             * Attachments
             * @default null
             */
            attachments?: components["schemas"]["Attachment"][] | null;
            /** Content */
            content: string;
            /**
             * Created At
             * @default null
             */
            created_at?: string | null;
            /** @default null */
            grading?: components["schemas"]["GradingResultDto"] | null;
            role: components["schemas"]["MessageRole"];
        };
        /**
         * MessageRole
         * @description Safe message roles exposed to API clients.
         * @enum {string}
         */
        MessageRole: "user" | "assistant";
        /**
         * PendingHandoff
         * @description A handoff paused for a future confirmation or rejection.
         */
        PendingHandoff: {
            /** Interrupt Id */
            interrupt_id: string;
            request: components["schemas"]["HandoffRequest"];
        };
        /**
         * PendingHandoffResponse
         * @description The current handoff approval state for one session.
         */
        PendingHandoffResponse: {
            /** @default null */
            pending_handoff?: components["schemas"]["PendingHandoff"] | null;
            /** Session Id */
            session_id: string;
        };
        /**
         * PendingToolApproval
         * @description A tool invocation paused at a resumable graph gate.
         */
        PendingToolApproval: {
            /** Interrupt Id */
            interrupt_id: string;
            request: components["schemas"]["ToolApprovalRequest"];
        };
        /** PendingToolApprovalResponse */
        PendingToolApprovalResponse: {
            /** @default null */
            pending_tool_approval?: components["schemas"]["PendingToolApproval"] | null;
            /** Session Id */
            session_id: string;
        };
        /**
         * RunError
         * @description A stable, sanitized error response for a completed run.
         */
        RunError: {
            /** @default null */
            agent?: components["schemas"]["AgentRole"] | null;
            /** Error Code */
            error_code: components["schemas"]["ErrorCode"] | components["schemas"]["ApiErrorCode"];
            /** Message */
            message: string;
        };
        /**
         * RunEvent
         * @description A replayable process event emitted during one run.
         */
        RunEvent: {
            /** @default null */
            agent?: components["schemas"]["AgentRole"] | null;
            /**
             * Content
             * @default null
             */
            content?: string | null;
            /**
             * Degraded
             * @default null
             */
            degraded?: boolean | null;
            /**
             * Duration Ms
             * @default null
             */
            duration_ms?: number | null;
            /** @default null */
            error_code?: components["schemas"]["ErrorCode"] | null;
            event_type: components["schemas"]["StreamEventType"];
            /**
             * Input Summary
             * @default null
             */
            input_summary?: string | null;
            /**
             * Is Delta
             * @default null
             */
            is_delta?: boolean | null;
            /**
             * Message Id
             * @default null
             */
            message_id?: string | null;
            /**
             * Output Stream
             * @default null
             */
            output_stream?: ("stdout" | "stderr") | null;
            /**
             * Output Summary
             * @default null
             */
            output_summary?: string | null;
            /**
             * Parent Tool Call Id
             * @default null
             */
            parent_tool_call_id?: string | null;
            /**
             * Plan Step Sequence
             * @default null
             */
            plan_step_sequence?: number | null;
            /**
             * Run Id
             * @default null
             */
            run_id?: string | null;
            /** Sequence */
            sequence: number;
            /**
             * Session Id
             * @default null
             */
            session_id?: string | null;
            /**
             * Success
             * @default null
             */
            success?: boolean | null;
            /**
             * Tool Call Id
             * @default null
             */
            tool_call_id?: string | null;
            /**
             * Tool Name
             * @default null
             */
            tool_name?: string | null;
        };
        /**
         * SearchHitDto
         * @description 检索命中的脱敏表示:chunk 摘要(截断)+ 逻辑 source 引用 + 分数。
         */
        SearchHitDto: {
            citation: components["schemas"]["Citation"];
            /** Score */
            score: number;
            /** Summary */
            summary: string;
        };
        /**
         * Session
         * @description A session visible to its owner.
         */
        Session: {
            /** Additional Workspace Roots */
            additional_workspace_roots?: string[];
            /** Archived */
            archived: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Session Id */
            session_id: string;
            /**
             * Title
             * @default null
             */
            title?: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** User Id */
            user_id: string | null;
            /** @default read_only */
            workspace_access?: components["schemas"]["WorkspaceAccess"];
            /** Workspace Root */
            workspace_root: string;
        };
        /**
         * SessionProcess
         * @description 刷新或切回会话时用于重放协作过程的权威快照。
         */
        SessionProcess: {
            /** @default null */
            current_agent?: components["schemas"]["AgentRole"] | null;
            /** Events */
            events?: components["schemas"]["RunEvent"][];
            /** @default null */
            pending_tool_approval?: components["schemas"]["PendingToolApproval"] | null;
            /**
             * Run Id
             * @default null
             */
            run_id?: string | null;
            /** @default null */
            task_plan?: components["schemas"]["TaskPlan"] | null;
            /**
             * Task Results
             * @default null
             */
            task_results?: components["schemas"]["TaskResult"][] | null;
        };
        /**
         * StatsOverview
         * @description 学习进度基础统计(只读聚合,依赖既有 SessionStore/Graph 能力)。
         *
         *     - agent_answer_counts 的键是 AgentRole 的字符串值(supervisor /
         *       teaching_assistant / learning_assistant / evaluator),口径与
         *       api/sessions._safe_agent 一致:识别不出角色的回答不计入任何键;
         *     - last_activity_at 为 ISO 时间戳,取当前用户所有会话 created_at
         *       的最大值(langchain-core 的 BaseMessage 无 created_at 字段,
         *       消息级时间不可用,见 api/stats.py 注释);无任何会话时为 None。
         */
        StatsOverview: {
            /** Agent Answer Counts */
            agent_answer_counts: {
                [key: string]: number;
            };
            /** Last Activity At */
            last_activity_at: string | null;
            /** Message Count */
            message_count: number;
            /** Session Count */
            session_count: number;
        };
        /**
         * StreamEvent
         * @description SSE 流式事件(D1-T1):基于 RunEvent 扩展内容字段。
         *
         *     - tool_call / tool_result 仅携带 core 已有界、脱敏的输入/输出摘要;
         *     - thinking 是固定阶段文案，reasoning 才是 provider 显式返回的字段;
         *     - message_end 事件的 content 是最终消息全文(与 POST /chat 的
         *       ChatResponse.message.content 同源)。
         *     error_code 复用 RunError 的联合类型:流式 error 事件需要携带
         *     ApiErrorCode(SESSION_BUSY / INTERNAL_ERROR),仅 ErrorCode 装不下。
         */
        StreamEvent: {
            /** @default null */
            agent?: components["schemas"]["AgentRole"] | null;
            /**
             * Citations
             * @default null
             */
            citations?: components["schemas"]["Citation"][] | null;
            /**
             * Content
             * @default null
             */
            content?: string | null;
            /** @default null */
            current_agent?: components["schemas"]["AgentRole"] | null;
            /**
             * Duration Ms
             * @default null
             */
            duration_ms?: number | null;
            /**
             * Error Code
             * @default null
             */
            error_code?: components["schemas"]["ErrorCode"] | components["schemas"]["ApiErrorCode"] | null;
            event_type: components["schemas"]["StreamEventType"];
            /** @default null */
            grading?: components["schemas"]["GradingResultDto"] | null;
            /**
             * Input Summary
             * @default null
             */
            input_summary?: string | null;
            /**
             * Is Delta
             * @default null
             */
            is_delta?: boolean | null;
            /** @default null */
            message?: components["schemas"]["Message"] | null;
            /**
             * Message Id
             * @default null
             */
            message_id?: string | null;
            /**
             * Output Stream
             * @default null
             */
            output_stream?: ("stdout" | "stderr") | null;
            /**
             * Output Summary
             * @default null
             */
            output_summary?: string | null;
            /**
             * Parent Tool Call Id
             * @default null
             */
            parent_tool_call_id?: string | null;
            /** @default null */
            pending_tool_approval?: components["schemas"]["PendingToolApproval"] | null;
            /**
             * Plan Step Sequence
             * @default null
             */
            plan_step_sequence?: number | null;
            /**
             * Run Id
             * @default null
             */
            run_id?: string | null;
            /** Sequence */
            sequence: number;
            /** Session Id */
            session_id: string;
            /**
             * Success
             * @default null
             */
            success?: boolean | null;
            /**
             * Tool Call Id
             * @default null
             */
            tool_call_id?: string | null;
            /**
             * Tool Name
             * @default null
             */
            tool_name?: string | null;
        };
        /**
         * StreamEventType
         * @description Public SSE protocol for token deltas and safe execution events.
         * @enum {string}
         */
        StreamEventType: "thinking" | "reasoning" | "tool_call" | "tool_result" | "tool_output" | "approval_required" | "message_delta" | "message_end" | "agent_switch" | "error" | "done";
        /**
         * TaskPlan
         * @description A task plan reserved for future chat responses.
         */
        TaskPlan: {
            /** Current Step Index */
            current_step_index: number;
            status: components["schemas"]["TaskPlanStatus"];
            /** Steps */
            steps: components["schemas"]["TaskPlanStep"][];
        };
        /**
         * TaskPlanStatus
         * @description Public task-plan status values.
         * @enum {string}
         */
        TaskPlanStatus: "active" | "completed" | "cancelled" | "failed";
        /**
         * TaskPlanStep
         * @description One planned worker task.
         */
        TaskPlanStep: {
            /** Description */
            description: string;
            /** Sequence */
            sequence: number;
            target_agent: components["schemas"]["WorkerAgentRole"];
        };
        /**
         * TaskResult
         * @description A completed or failed task-plan step.
         */
        TaskResult: {
            /** @default null */
            error_code?: components["schemas"]["ErrorCode"] | null;
            /**
             * Output
             * @default null
             */
            output?: string | null;
            /** Step Sequence */
            step_sequence: number;
            /** Success */
            success: boolean;
            target_agent: components["schemas"]["WorkerAgentRole"];
        };
        /**
         * ToolApprovalDecisionAction
         * @enum {string}
         */
        ToolApprovalDecisionAction: "confirm" | "reject";
        /** ToolApprovalDecisionRequest */
        ToolApprovalDecisionRequest: {
            action: components["schemas"]["ToolApprovalDecisionAction"];
            /** Interrupt Id */
            interrupt_id: string;
        };
        /**
         * ToolApprovalRequest
         * @description The exact validated invocation shown to the user before execution.
         */
        ToolApprovalRequest: {
            agent_role: components["schemas"]["AgentRole"];
            /** Arguments */
            arguments: {
                [key: string]: unknown;
            };
            /** Tool Call Id */
            tool_call_id: string;
            /** Tool Name */
            tool_name: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WorkerAgentRole
         * @description Roles that can receive a handoff or task-plan step.
         * @enum {string}
         */
        WorkerAgentRole: "teaching_assistant" | "learning_assistant" | "evaluator";
        /**
         * WorkspaceAccess
         * @description Access level granted to Agent filesystem tools for a session.
         * @enum {string}
         */
        WorkspaceAccess: "read_only";
        /**
         * WorkspaceDirectory
         * @description One directory entry in the server-side workspace picker.
         */
        WorkspaceDirectory: {
            /** Name */
            name: string;
            /** Path */
            path: string;
        };
        /**
         * WorkspaceDirectoryListing
         * @description Directory picker state rooted in the server filesystem.
         */
        WorkspaceDirectoryListing: {
            /** Directories */
            directories?: components["schemas"]["WorkspaceDirectory"][];
            /** Parent */
            parent?: string | null;
            /** Path */
            path: string;
        };
        /**
         * WorkspacePath
         * @description A canonical existing directory accepted by the server policy.
         */
        WorkspacePath: {
            /** Name */
            name: string;
            /** Path */
            path: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    chat_chat_post: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    chat_stream_chat_stream_post: {
        parameters: {
            query?: {
                from_sequence?: number;
            };
            header?: {
                "x-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_feedback_feedback_post: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    upload_file_files_post: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_file_files_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileUploadResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_uploaded_file_files__file_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: string | null;
            };
            path: {
                file_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_chunk_knowledge_chunks__chunk_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chunk_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChunkDetailResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_documents_knowledge_documents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeDocumentListResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    upload_document_knowledge_documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_knowledge_documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeDocumentUploadResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_document_knowledge_documents__document_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_document_chunks_knowledge_documents__document_id__chunks_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChunkListResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    knowledge_overview_knowledge_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeOverviewResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    search_knowledge_knowledge_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnowledgeSearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeSearchResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    diagnosis_summary_learning_diagnosis_summary_get: {
        parameters: {
            query?: {
                student_id?: string | null;
            };
            header?: {
                "x-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosisSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_sessions_get: {
        parameters: {
            query?: {
                include_archived?: boolean;
            };
            header?: {
                "x-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"][];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_session_sessions_post: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    archive_session_sessions__session_id__archive_post: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_pending_handoff_sessions__session_id__handoff_get: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingHandoffResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    decide_handoff_sessions__session_id__handoff_post: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HandoffDecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_session_history_sessions__session_id__messages_get: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_session_process_sessions__session_id__process_get: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionProcess"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_pending_tool_approval_sessions__session_id__tool_approval_get: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingToolApprovalResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    decide_tool_approval_sessions__session_id__tool_approval_post: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ToolApprovalDecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    stream_tool_approval_sessions__session_id__tool_approval_stream_post: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ToolApprovalDecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    add_workspace_root_sessions__session_id__workspace_roots_post: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddWorkspaceRootRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    stats_overview_stats_overview_get: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsOverview"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_workspace_directories_workspaces_directories_get: {
        parameters: {
            query?: {
                path?: string | null;
            };
            header?: {
                "x-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceDirectoryListing"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    validate_workspace_workspaces_validate_post: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddWorkspaceRootRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspacePath"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
