/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat
         * @description Run one synchronous collaboration turn in a worker thread.
         */
        post: operations["chat_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sessions
         * @description List only the current user's sessions.
         */
        get: operations["list_sessions_sessions_get"];
        put?: never;
        /**
         * Create Session
         * @description Create a session within the current user's isolated namespace.
         */
        post: operations["create_session_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Archive Session
         * @description Archive an active session without revealing another user's session.
         */
        post: operations["archive_session_sessions__session_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Session History
         * @description Return only safe history fields for the current user's session.
         */
        get: operations["get_session_history_sessions__session_id__messages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgentRole
         * @description Public collaborative-agent roles.
         * @enum {string}
         */
        AgentRole: "supervisor" | "teaching_assistant" | "learning_assistant" | "evaluator";
        /**
         * ApiErrorCode
         * @description Stable HTTP API errors not emitted by a graph run.
         * @enum {string}
         */
        ApiErrorCode: "invalid_request" | "internal_error" | "session_already_exists" | "session_busy" | "session_not_found";
        /**
         * ChatRequest
         * @description One synchronous user message for a session.
         */
        ChatRequest: {
            /** Message */
            message: string;
            /** Session Id */
            session_id: string;
        };
        /**
         * ChatResponse
         * @description The synchronous chat response contract reserved for W0-T4.
         */
        ChatResponse: {
            /** @default null */
            current_agent?: components["schemas"]["AgentRole"] | null;
            /** Events */
            events?: components["schemas"]["RunEvent"][];
            /** @default null */
            message?: components["schemas"]["Message"] | null;
            /** @default null */
            pending_handoff?: components["schemas"]["PendingHandoff"] | null;
            /**
             * References
             * @default null
             */
            references?: components["schemas"]["Citation"][] | null;
            /** @default null */
            run_error?: components["schemas"]["RunError"] | null;
            /** Session Id */
            session_id: string;
            /** @default null */
            task_plan?: components["schemas"]["TaskPlan"] | null;
            /**
             * Task Results
             * @default null
             */
            task_results?: components["schemas"]["TaskResult"][] | null;
        };
        /**
         * Citation
         * @description A safe reference placeholder for future retrieval-backed responses.
         */
        Citation: {
            /** Chunk Id */
            chunk_id: string;
            /** Document Id */
            document_id: string;
            /**
             * Page
             * @default null
             */
            page?: number | null;
            /** Source */
            source: string;
        };
        /**
         * CreateSessionRequest
         * @description Optional client-selected ID for a new session.
         */
        CreateSessionRequest: {
            /**
             * Session Id
             * @default null
             */
            session_id?: string | null;
        };
        /**
         * ErrorCode
         * @description Stable API error codes aligned with the current Core classification.
         * @enum {string}
         */
        ErrorCode: "tool_unknown" | "tool_unauthorized" | "tool_invalid_arguments" | "tool_execution_failed" | "tool_timeout" | "model_call_failed" | "react_iteration_limit" | "graph_handoff_limit" | "graph_switch_limit" | "graph_invalid_target" | "graph_aggregation_invalid" | "agent_output_invalid";
        /**
         * ErrorDetail
         * @description A sanitized stable API error.
         */
        ErrorDetail: {
            error_code: components["schemas"]["ApiErrorCode"];
            /** Message */
            message: string;
        };
        /**
         * ErrorResponse
         * @description FastAPI's standard error envelope.
         */
        ErrorResponse: {
            detail: components["schemas"]["ErrorDetail"];
        };
        /**
         * HandoffRequest
         * @description The information a user reviews before a worker handoff.
         */
        HandoffRequest: {
            /**
             * Plan Step Sequence
             * @default null
             */
            plan_step_sequence?: number | null;
            target_agent: components["schemas"]["WorkerAgentRole"];
            /** Task Content */
            task_content: string;
        };
        /**
         * Message
         * @description A safe user or assistant message.
         */
        Message: {
            /** @default null */
            agent?: components["schemas"]["AgentRole"] | null;
            /** Content */
            content: string;
            /**
             * Created At
             * @default null
             */
            created_at?: string | null;
            role: components["schemas"]["MessageRole"];
        };
        /**
         * MessageRole
         * @description Safe message roles exposed to API clients.
         * @enum {string}
         */
        MessageRole: "user" | "assistant";
        /**
         * PendingHandoff
         * @description A handoff paused for a future confirmation or rejection.
         */
        PendingHandoff: {
            /** Interrupt Id */
            interrupt_id: string;
            request: components["schemas"]["HandoffRequest"];
        };
        /**
         * RunError
         * @description A stable, sanitized error response for a completed run.
         */
        RunError: {
            /** @default null */
            agent?: components["schemas"]["AgentRole"] | null;
            /** Error Code */
            error_code: components["schemas"]["ErrorCode"] | components["schemas"]["ApiErrorCode"];
            /** Message */
            message: string;
        };
        /**
         * RunEvent
         * @description A safe incremental event emitted during one run.
         */
        RunEvent: {
            /** @default null */
            agent?: components["schemas"]["AgentRole"] | null;
            /**
             * Degraded
             * @default null
             */
            degraded?: boolean | null;
            /**
             * Duration Ms
             * @default null
             */
            duration_ms?: number | null;
            /** @default null */
            error_code?: components["schemas"]["ErrorCode"] | null;
            event_type: components["schemas"]["StreamEventType"];
            /**
             * Plan Step Sequence
             * @default null
             */
            plan_step_sequence?: number | null;
            /** Sequence */
            sequence: number;
            /**
             * Session Id
             * @default null
             */
            session_id?: string | null;
            /**
             * Success
             * @default null
             */
            success?: boolean | null;
            /**
             * Tool Name
             * @default null
             */
            tool_name?: string | null;
        };
        /**
         * Session
         * @description A session visible to its owner.
         */
        Session: {
            /** Archived */
            archived: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Session Id */
            session_id: string;
            /** User Id */
            user_id: string | null;
        };
        /**
         * StreamEventType
         * @description Public event protocol reserved for future streaming support.
         * @enum {string}
         */
        StreamEventType: "thinking" | "tool_call" | "tool_result" | "message_end" | "agent_switch" | "error" | "done";
        /**
         * TaskPlan
         * @description A task plan reserved for future chat responses.
         */
        TaskPlan: {
            /** Current Step Index */
            current_step_index: number;
            status: components["schemas"]["TaskPlanStatus"];
            /** Steps */
            steps: components["schemas"]["TaskPlanStep"][];
        };
        /**
         * TaskPlanStatus
         * @description Public task-plan status values.
         * @enum {string}
         */
        TaskPlanStatus: "active" | "completed" | "cancelled" | "failed";
        /**
         * TaskPlanStep
         * @description One planned worker task.
         */
        TaskPlanStep: {
            /** Description */
            description: string;
            /** Sequence */
            sequence: number;
            target_agent: components["schemas"]["WorkerAgentRole"];
        };
        /**
         * TaskResult
         * @description A completed or failed task-plan step.
         */
        TaskResult: {
            /** @default null */
            error_code?: components["schemas"]["ErrorCode"] | null;
            /**
             * Output
             * @default null
             */
            output?: string | null;
            /** Step Sequence */
            step_sequence: number;
            /** Success */
            success: boolean;
            target_agent: components["schemas"]["WorkerAgentRole"];
        };
        /**
         * WorkerAgentRole
         * @description Roles that can receive a handoff or task-plan step.
         * @enum {string}
         */
        WorkerAgentRole: "teaching_assistant" | "learning_assistant" | "evaluator";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    chat_chat_post: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_sessions_sessions_get: {
        parameters: {
            query?: {
                include_archived?: boolean;
            };
            header?: {
                "x-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"][];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_session_sessions_post: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    archive_session_sessions__session_id__archive_post: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_session_history_sessions__session_id__messages_get: {
        parameters: {
            query?: never;
            header?: {
                "x-user-id"?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
